routes/web.php
<?php
use App\Nav;
use App\Body;
use App\SideBar;
use App\Footer;
use App\Page;
use App\Comment;
use App\Report;
use App\ServiceAttribute;
use Illuminate\Support\Facades\Storage;
use App\Http\Response;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>''], function() {

	//Base Authentication
	Route::get('/index','BaseAuthController@index')->name('base_auth');
 	Route::post('/base_form_post','BaseAuthController@store')->name('base_form_post');
 	Route::get('/base_login_get','BaseAuthLoginController@index')->name('base_login_get');
 	Route::post('/base_login_post','BaseAuthLoginController@store')->name('base_login_post');

 	//Logout
 	Route::get('logout',function(){
 		Auth::logout();
        request()->session()->forget('msg');
 		return redirect('/');
 	});
 	//Web Layout
	Route::get('/', function () {
		
		$nav=Nav::all();
		$n=Nav::where('Nav_Icon','!=',null)->get();
		$page=Page::first();
		$type=Body::pluck('Body_type');
		$footer11=Footer::where(['F_header_type'=>1,'F_content_type'=>1])->get();
		$footer22=Footer::where(['F_header_type'=>2,'F_content_type'=>2])->get();
		$footer33=Footer::where(['F_header_type'=>3,'F_content_type'=>3])->get();
		$footer44=Footer::where(['F_header_type'=>4,'F_content_type'=>4])->get();
		$comments=Comment::all();
		$report=Report::all();
		$service=ServiceAttribute::all();

		return view('Pages.index',compact('page','type','nav','n','footer11','footer22','footer33','footer44','comments','report','service'));
	})->name('welcome');

	Route::get('test_login',function(){
		return view('welcome');
	})->name('test_login');
	
	Route::get('download_report/{report}',function(Report $report){
		$path=public_path('storage/'.$report->upload_report);
		return response()->download($path);
	})->name('report_down');

	Route::get('page',function(){
		return view('pages');
	})->name('page_form');

	Route::get('service_attribute_dashboard',function(){
		$service=ServiceAttribute::all();
		return view('UI/service_attribute_dashboard',compact('service'));
	})->name('service_attribute_dashboard');
});

//Home Group
Route::group(['prefix'=>''],function(){
	Auth::routes();
	Route::get('/home', 'HomeController@index')->name('home');
});

//Report+Blog Group
Route::group(['prefix'=>''],function(){
	Route::post('comment/{report}','CommentController@store')->name('comment.store');
	Route::delete('comment/{postscomment}','CommentController@destroy')->name('comment.delete');
	Route::get('new_page/{page}','PageController@show')->name('new.page');
	Route::get('new_page/{pages}','PageController@show_profile')->name('new.page_profile');
});

//Resource Controllers for CRUD
Route::group(['namespace'=>'UI'],function(){
	Route::resource('nav','NavController');
	Route::resource('body','BodyController');
	Route::resource('sidebar','SideBarController');
	Route::resource('footer','FooterController');
	Route::resource('report','ReportController');
	Route::resource('service','ServiceAttributeController');
	Route::get('link/{link}/content','NavController@link')->name('nav.link');
	Route::get('preview_report','ReportController@preview')->name('preview');
});

Route::group(['namespace' => '/'],function(){
	//UserList
	Route::get('user_list',function(){
		return view('base_UI.admin.user_dashboard');
	})->name('user_dash');
});

resources/views/base_UI/admin/body_dashboard.blade.php
@extends('base_UI.admin.layout_admin')

@push('css-links')
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
@endpush

@section('bodyDash')
	<div class="card">
		<div class="card-header">
			<ul class="nav mt-2 mb-2 ml-2 mr-2">
				<li class="nav-item mr-2">
					<a href="{{ route('body.index') }}"><img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28"></a>
				</li>
				<li class="nav-item ml-2">
					<a href="{{ route('body.index') }}">Home</a>
				</li>
			</ul>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-2">
					<a href="{{ route('body.create') }}"><button class="btn btn-success mt-2 mb-2">Create Body</button></a>
				</div>
				<div class="col-sm-2">
					<a href="{{ route('body.index') }}"><button class="btn btn-primary mt-2 mb-2">List of Bodies</button></a>
				</div>
				<div class="col-sm-6"></div>
			</div>
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<table class="table table-bordered">
						<thead class="thead-dark">
							<tr>
								<th>#</th>
								<th>Name</th>
								<th>Body Type</th>
								<th>Parent ID</th>
								<th>Created_at</th>
								<th>Updated_at</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							@foreach ($body as $element)
								<tr>
									<td>{{ $element->id }}</td>
									<td>{{ $element->Name }}</td>
									<td>{{ $element->Body_type }}</td>
									<td>{{ $element->Parent_id }}</td>
									<td>{{ $element->created_at }}</td>
									<td>{{ $element->updated_at }}</td>
									<td>
										<a href="{{ route('body.edit',$element->id) }}"><i class="fas fa-pencil-alt"></i></a>
										<form action="{{ route('body.destroy',$element->id) }}" method="POST">
											@method('DELETE')
											{{ csrf_field() }}
											<button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
										</form>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
				<div class="col-sm-2"></div>
			</div>
		</div>
	</div>
@endsection

resources/views/base_UI/admin/body_form.blade.php
@extends('base_UI.admin.layout_admin')

@section('bodyForm')
	<div class="card">
		<div class="card-header">
			<ul class="nav ml-2 mt-2 mr-2 mb-2">
				<li class="nav-item mr-2">
					<a class="nav-link" href="{{ route('body.index') }}"><img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28"></a>
				</li>
				<li class="nav-item ml-2">
					<a href="{{ route('body.index') }}">Home</a>
				</li>
			</ul>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-sm-2">
					
				</div>
				<div class="col-sm-2">
					
				</div>
				<div class="col-sm-8"></div>
			</div>
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<form action="{{ route('body.store') }}" method="POST" enctype="multipart/form-data">
						{{ csrf_field() }}
						<h6>Name:</h6><input type="text" name="name" class="form-control" placeholder="Enter Your Name" required>
						<br>
						<h6>Parent Id:</h6><input type="text" name="parent" class="form-control" placeholder="Enter Your Parent Id" required>
						<br>
						<h6>Description:</h6><textarea name="body_description" id="body_description" cols="30" rows="10" class="form-control" placeholder="Enter Your Body Description"></textarea>
						<br>
						<h6>Body_type:</h6><input type="text" name="body_type" class="form-control" placeholder="Enter Body Type">
						<br>
						<h6>Body_Icon URL:</h6><input type="text" name="body_icon" placeholder="Enter Body Icon" class="form-control">
						<br>
						<h6>Upload File Here:</h6><input type="file" name="body_file" placeholder="Upload Your File" class="form-control">
						<br>
						<h6><input type="checkbox" name="remember">remember me</h6>
						<br>
						<input type="submit" value="Save" class="btn btn-success mt-2 mb-2">
					</form>
				</div>
				<div class="col-sm-2"></div>
			</div>
		</div>
	</div>
@endsection

resources/views/base_UI/admin/footer_dashboard.blade.php
@extends('base_UI.admin.layout_admin')
@push('css-links')
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
@endpush

@section('footerDash')
	<div class="card">
		<div class="card-header">
			<ul class="nav">
				<li class="nav-item">
					<a href="{{ route('footer.index') }}"><img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28" class="nav-link"></a>
				</li>
				<li class="nav-item">
					<a href="{{ route('footer.index') }}" class="nav-link">Home</a>
				</li>
			</ul>
		</div>
		<div class="card-body">
			<div class="row mt-2 mb-2 pb-2 pt-2">
				<div class="col-sm-2"></div>
				<div class="col-sm-2">
					<a href="{{ route('footer.create') }}"><button class="btn btn-success">Create Footer</button></a>
				</div>
				<div class="col-sm-2">
					<a href="{{ route('footer.index') }}"><button class="btn btn-primary">List of Footers</button></a>
				</div>
				<div class="col-sm-6"></div>
			</div>
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<table class="table table-bordered">
						<thead class="thead-dark">
							<tr>
								<th>#</th>
								<th>Footer Header</th>
								<th>Footer Header Type</th>
								<th>Footer Content Type</th>
								<th>Created_at</th>
								<th>Updated_at</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							@foreach ($footer as $element)
								<tr>
									<td>{{ $element->id }}</td>
									<td>{{ $element->F_header }}</td>
									<td>{{ $element->F_header_type }}</td>
									<td>{{ $element->F_content_type }}</td>
									<td>{{ $element->created_at }}</td>
									<td>{{ $element->updated_at }}</td>
									<td>
										<a href="{{ route('footer.edit',$element->id) }}"><i class="fas fa-pencil-alt"></i></a>
										<form action="{{ route('footer.destroy',$element->id) }}">
											@method('PUT')
											{{ csrf_field() }}
											<button class="btn btn-danger" type="submit"><i class="fas fa-trash-alt"></i></button>
										</form>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
				<div class="col-sm-2">
					
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/base_UI/admin/footer_edit.blade.php
@extends('base_UI.admin.layout_admin')

@section('footerEdit')
	<div class="card">
		<div class="card-header">
			<ul class="nav">
				<li class="nav-item">
					<a href="{{ route('footer.index') }}" class="nav-link"><img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28" class="nav-link"></a>
				</li>
				<li class="nav-item">
					<a href="{{ route('footer.index') }}" class="nav-link">Home</a>
				</li>
			</ul>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-2">
					<a href="{{ route('footer.create') }}"><button class="btn btn-primary">List of Footers</button></a>
				</div>
				<div class="col-sm-8"></div>
			</div>
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<form action="{{ route('footer.update',$footer->id) }}" method="POST" enctype="multipart/form-data">
						@method('PUT')
						{{ csrf_field() }}
						<h6>Parent ID:</h6><input type="text" name="f_parent" value="{{ $footer->Parent_id }}" class="form-control" placeholder="Enter Your Parent ID">
						<br>
						<h6>Footer Header:</h6><input type="text" name="f_header" value="{{ $footer->F_header }}" class="form-control" placeholder="Enter Your Footer Header">
						<br>
						<h6>Footer Content:</h6><input type="text" name="f_content" value="{{ $footer->F_content }}" class="form-control" placeholder="Enter Footer Content">
						<br>
						<h6>Footer Header Type:</h6><input type="text" name="f_header_type" value="{{ $footer->F_header_type }}" class="form-control" placeholder="Enter Footer Header Type">
						<br>
						<h6>Footer Content Type:</h6><input type="text" name="f_content_type" value="{{ $footer->F_content_type }}" class="form-control" placeholder="Enter Footer Content Type">
						<br>
						<h6>Upload File Here:</h6><input type="file" name="f_upload" class="form-control">
						<br>
						<h6>Footer Icon URL:</h6><input type="text" name="footer_icon" value="{{ $footer->Footer_Icon }}" class="form-control" placeholder="Enter Footer Icon">
						<br>
						<input type="checkbox" name="remember" checked="{{ !empty($footer->remember) ? true:false }}"><h6>Remember me</h6>
						<br>
						<input type="submit" name="submit" value="Save">
					</form>
				</div>
				<div class="col-sm-2"></div>
			</div>
		</div>
	</div>
@endsection

resources/views/base_UI/admin/nav_dashboard.blade.php
@extends('base_UI.admin.layout_admin')

@push('css-links')
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
@endpush

@section('navDash')
	<div class="card">
		<div class="card-header">
			<ul class="nav">
				<li class="nav-item">
					<a href="{{ route('nav.index') }}" class="nav-link">
						<img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28">
					</a>
				</li>
				<li class="nav-item">
					<a href="{{ route('nav.index') }}" class="nav-link">Home</a>
				</li>
			</ul>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-sm-2">
					
				</div>
				<div class="col-sm-8">
					<div class="row">
						<div class="col-sm-2">
							<a href="{{ route('nav.create') }}"><button class="btn btn-success mt-2 mb-2">Create NavBar</button></a>
						</div>
						<div class="col-sm-2">
							<a href="{{ route('nav.index') }}"><button class="btn btn-primary mt-2 mb-2">List of NavBar</button></a>
						</div>
						<div class="col-sm-8"></div>
					</div>
					<table class="table table-bordered">
						<thead class="thead-dark">
							<tr>
								<th>#</th>
								<th>Name</th>
								<th>Created_at</th>
								<th>Updated_at</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							@foreach ($nav as $element)
								<tr>
									<td>{{ $element->id }}</td>
									<td>{{ $element->Dropdown_link }}</td>
									<td>{{ $element->created_at }}</td>
									<td>{{ $element->updated_at }}</td>
									<td>
										<a href="{{ route('nav.edit',$element->id) }}"><i class="fas fa-pencil-alt"></i></a>
										<form action="{{ route('nav.destroy',$element->id) }}" method="POST">
											@method('DELETE')
											{{ csrf_field() }}
											<button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
										</form>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
				<div class="col-sm-2">
					
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/base_UI/admin/nav_edit.blade.php
@extends('base_UI.admin.layout_admin')


@section('navEdit')
	<div class="card">
		<div class="card-header">
			<ul class="nav">
				<li class="nav-item">
					<a href="{{ route('nav.index') }}" class="nav-link"><img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28"></a>
				</li>
				<li class="nav-item">
					<a href="{{ route('nav.index') }}" class="nav-link">Home</a>
				</li>
			</ul>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-2">
					<a href="{{ route('nav.create') }}"><button class="btn btn-success mt-2 mb-2">Create NavBar</button></a>
				</div>
				<div class="col-sm-2">
					<a href="{{ route('nav.index') }}"><button class="btn btn-primary mt-2 mb-2">List of NavBar</button></a>
				</div>
				<div class="col-sm-6"></div>
			</div>
			<div class="row mt-2 pt-2">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<form action="{{ route('nav.update',$nav->id) }}" method="POST" enctype="multipart/form-data">
						{{ csrf_field() }}
						<h6>Dropdown_link:</h6><input type="text" name="drop_link" value="{{ $nav->Dropdown_link }}" class="form-control" placeholder="Enter Nav Dropdown Link" required>
						<br>
						<h6>Dropdown_link_type:</h6><input type="text" name="drop_link_type" class="form-control" placeholder="Enter Dropdown Link Type" value="{{ $nav->Dropdown_link_type }}">
						<br>
						<h6>Nav Icon URL:</h6><input type="text" name="nav_icon" class="form-control" value="{{ $nav->Nav_Icon }}" placeholder="Enter Nav Icon URL">
						<br>
						<input type="checkbox" checked="{{ !empty('remember') ? true : false }}" name="remember">
                        remember me
						<br>
						<input type="submit" name="submit" value="Update" class="btn btn-success mt-2 mb-2">
					</form>	
				</div>
				<div class="col-sm-2"></div>
			</div>
		</div>
	</div>	
@endsection

resources/views/base_UI/admin/service_attribute_dashboard.blade.php
@extends('base_UI.admin.layout_admin')
@push('css-links')
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
@endpush

@section('serviceDash')
	<div class="card">
		<div class="card-header">
			<ul class="nav">
				<li class="nav-item">
					<a href="{{ route('service.index') }}" class="nav-link"><img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28"></a>
				</li>
				<li class="nav-item">
					<a href="{{ route('service.index') }}" class="nav-link">Home</a>
				</li>
			</ul>	
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-2 mb-2 pb-2">
					<a href="{{ route('service.create') }}"><button class="btn btn-success">Create Service</button></a>
				</div>
				<div class="col-sm-2">
					<a href="{{ route('service.index') }}"><button class="btn btn-primary">List of Services</button></a>
				</div>
				<div class="col-sm-6"></div>
			</div>
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<table class="table table-bordered">
						<thead class="thead-dark">
							<tr>
								<th>#</th>
								<th>Project_Category</th>
								<th>Date</th>
								<th>Project_Status</th>
								<th>Project_Ranking</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							@foreach ($service as $element)
								<tr>
									<td>{{ $element->id }}</td>
									<td>{{ $element->project_category }}</td>
									<td>{{ $element->date }}</td>
									<td>{{ $element->project_status }}</td>
									<td>{{ $element->project_ranking }}</td>
									<td>
										<a href="{{ route('service.edit',$element->id) }}"><i class="fas fa-pencil-alt"></i></a>
										<form action="{{ route('service.destroy',$element->id) }}" method="POST">
											@method('DELETE')
											{{ csrf_field() }}
											<button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
										</form>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
				<div class="col-sm-2"></div>
			</div>
		</div>
	</div>
@endsection

resources/views/base_UI/admin/service_attribute_edit.blade.php
@extends('base_UI.admin.layout_admin')

@section('serviceEdit')
	<div class="card">
		<div class="card-header">
			<ul class="nav">
				<li class="nav-item">
					<a href="{{ route('service.index') }}" class="nav-link"><img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28"></a>
				</li>
				<li class="nav-item">
					<a href="{{ route('service.index') }}" class="nav-link">Home</a>
				</li>
			</ul>
		</div>
		<div class="cardbody">
			<div class="row mt-2 pt-2">
				<div class="col-sm-2"></div>
				<div class="col-sm-2 mb-2 pb-2">
					<a href="{{ route('service.index') }}"><button class="btn btn-primary">List of Services</button></a>
				</div>
				<div class="col-sm-8"></div>
			</div>
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<form action="{{ route('service.update',$service->id) }}" method="POST" enctype="multipart/form-data">
						@method('PUT')
						{{ csrf_field() }}
						<h6>Service ID:</h6><input type="text" name="service_id" value="{{ $service->service_id }}" class="form-control" placeholder="Enter Your Service ID">
						<br>
						<h6>Project Category:</h6><input type="text" name="project_category" value="{{ $service->project_category }}" class="form-control" placeholder="Enter Project Category">
						<br>
						<h6>Date:</h6><input type="date" name="date" value="{{ $service->date }}" class="form-control" placeholder="Enter Date">
						<br>
						<h6>Project Status:</h6><input type="text" name="project_status" value="{{ $service->project_status }}" class="form-control" placeholder="Enter Project Status">
						<br>
						<h6>Project Ranking:</h6><input type="text" name="project_ranking" value="{{ $service->project_ranking }}" class="form-control" placeholder="Enter Project Ranking">
						<br>
						<h6>Project URL:</h6><input type="text" name="project_url" value="{{ $service->project_url }}" class="form-control" placeholder="Enter Project URL">
						<br>
						<input type="checkbox" name="remember" checked="{{ !empty('remember') ? true:false }}"><h6>remember me</h6>
						<br>
						<input type="submit" name="submit" class="btn btn-success mt-2 mb-2" value="Save">
					</form>
				</div>
				<div class="col-sm-2"></div>
			</div>
		</div>
	</div>
@endsection

resources/views/base_UI/admin/service_attribute_form.blade.php
@extends('base_UI.admin.layout_admin')

@section('serviceForm')
	<div class="card">
		<div class="card-header">
			<ul class="nav">
				<li class="nav-item">
					<a href="{{ route('service.index') }}" class="nav-link"><img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28"></a>
				</li>
				<li class="nav-item">
					<a href="{{ route('service.index') }}">Home</a>
				</li>
			</ul>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-2 mb-2 pb-2">
					<a href="{{ route('service.index') }}"><button class="btn btn-primary">List of Services</button></a>
				</div>
				<div class="col-sm-8"></div>
			</div>
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<form action="{{ route('service.store') }}" method="POST" enctype="multipart/form-data">
						{{ csrf_field() }}
						<h6>Service ID:</h6><input type="text" name="service_id" class="form-control" placeholder="Enter Your Service ID">
						<br>
						<h6>Project Category:</h6><input type="text" name="project_category" class="form-control" placeholder="Enter Project Category">
						<br>
						<h6>Date:</h6><input type="date" name="date" class="form-control" placeholder="Enter Date">
						<br>
						<h6>Project Status:</h6><input type="text" name="project_status" class="form-control" placeholder="Enter Project Status">
						<br>
						<h6>Project Ranking:</h6><input type="text" name="project_ranking" class="form-control" placeholder="Enter Project Ranking">
						<br>
						<h6>Project URL:</h6><input type="text" name="project_url" class="form-control" placeholder="Enter Project URL">
						<br>
						<input type="checkbox" name="remember"><h6>remember me</h6>
						<br>
						<input type="submit" name="submit" class="btn btn-success mt-2 mb-2" value="Save">
					</form>
				</div>
				<div class="col-sm-2"></div>
			</div>
		</div>
	</div>
@endsection

resources/views/base_UI/admin/side_edit.blade.php
@extends('base_UI.admin.layout_admin')

@section('sideEdit')
	<div class="card">
		<div class="card-header">
			<ul class="nav">
				<li class="nav-item">
					<a class="nav-link" href="{{ route('sidebar.index') }}"><img src="{{ asset('images/logo/redbrick.png') }}" alt="RedBrick_logo" width="112" height="28"></a>
				</li>
				<li class="nav-item">
					<a href="{{ route('sidebar.index') }}" class="nav-link">Home</a>
				</li>
			</ul>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-2">
					<a href="{{ route('sidebar.index') }}"><button class="btn btn-primary">List of Sidebar</button></a>	
				</div>
				<div class="col-sm-8"></div>
			</div>
			<div class="row">
				<div class="col-sm-2"></div>
				<div class="col-sm-8">
					<form action="{{ route('sidebar.update',$sidebar->id) }}" method="POST" enctype="multipart/form-data">
						@method('PUT')
						{{ csrf_field() }}
						<h6>Parent_ID:</h6><input type="text" name="parent_id" class="form-control" placeholder="Enter Parent ID" value="{{ $sidebar->Parent_id }}">
						<br>
						<h6>Name:</h6><input type="text" name="name" class="form-control" placeholder="Enter Name" value="{{ $sidebar->Name }}" required>
						<br>
						<h6>SideBar_type:</h6><input type="text" name="sidebar_type" class="form-control" placeholder="Enter Sidebar_type" value="{{ $sidebar->Sidebar_type }}">
						<br>
						<h6>Upload File:</h6><input type="file" class="form-control" placeholder="Upload File" name="side_file">
						<br>
						<h6>Sidebar Description:</h6><textarea name="description_side" class="form-control" id="description_side" cols="30" rows="10">{{ $sidebar->Description }}</textarea>
						<br>
						<h6>Facebook URL:</h6><input type="text" name="side_icon" class="form-control" placeholder="Enter FB URL" value="{{ $sidebar->Sidebar_Icon }}">
						<br>
						<input type="checkbox" name="remember" checked="{{ !empty('remember') ? true:false }}"><h6>remember me</h6>
					</form>
				</div>
				<div class="col-sm-2"></div>
			</div>
		</div>
	</div>
@endsection