routes/web.php
<?php
use App\Nav;
use App\Body;
use App\SideBar;
use App\Footer;
use App\Page;
use App\Comment;
use App\Report;
use App\ServiceAttribute;
use Illuminate\Support\Facades\Storage;
use App\Http\Response;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>''], function() {

	//Base Authentication
	Route::get('/index','BaseAuthController@index')->name('base_auth');
 	Route::post('/base_form_post','BaseAuthController@store')->name('base_form_post');
 	Route::get('/base_login_get','BaseAuthLoginController@index')->name('base_login_get');
 	Route::post('/base_login_post','BaseAuthLoginController@store')->name('base_login_post');

 	//Logout
 	Route::get('logout',function(){
 		Auth::logout();
        request()->session()->forget('msg');
 		return redirect('/');
 	});
 	//Web Layout
	Route::get('/', function () {
		
		$nav=Nav::all();
		$n=Nav::where('Nav_Icon','!=',null)->get();
		$page=Page::first();
		$type=Body::pluck('Body_type');
		$footer11=Footer::where(['F_header_type'=>1,'F_content_type'=>1])->get();
		$footer22=Footer::where(['F_header_type'=>2,'F_content_type'=>2])->get();
		$footer33=Footer::where(['F_header_type'=>3,'F_content_type'=>3])->get();
		$footer44=Footer::where(['F_header_type'=>4,'F_content_type'=>4])->get();
		$comments=Comment::all();
		$report=Report::all();
		$service=ServiceAttribute::all();

		return view('Pages.index',compact('page','type','nav','n','footer11','footer22','footer33','footer44','comments','report','service'));
	})->name('welcome');

	Route::get('test_login',function(){
		return view('welcome');
	})->name('test_login');
	
	Route::get('download_report/{report}',function(Report $report){
		$path=public_path('storage/'.$report->upload_report);
		return response()->download($path);
	})->name('report_down');

	Route::get('page',function(){
		return view('pages');
	})->name('page_form');

	Route::get('service_attribute_dashboard',function(){
		$service=ServiceAttribute::all();
		return view('UI/service_attribute_dashboard',compact('service'));
	})->name('service_attribute_dashboard');
});

//Home Group
Route::group(['prefix'=>''],function(){
	Auth::routes();
	Route::get('/home', 'HomeController@index')->name('home');
});

//Report+Blog Group
Route::group(['prefix'=>''],function(){
	Route::post('comment/{report}','CommentController@store')->name('comment.store');
	Route::delete('comment/{postscomment}','CommentController@destroy')->name('comment.delete');
	Route::get('new_page/{page}','PageController@show')->name('new.page');
	Route::get('new_page/{pages}','PageController@show_profile')->name('new.page_profile');
});

//Resource Controllers for CRUD
Route::group(['namespace'=>'UI'],function(){
	Route::resource('nav','NavController');
	Route::resource('body','BodyController');
	Route::resource('sidebar','SideBarController');
	Route::resource('footer','FooterController');
	Route::resource('report','ReportController');
	Route::resource('service','ServiceAttributeController');
	Route::get('link/{link}/content','NavController@link')->name('nav.link');
	Route::get('preview_report','ReportController@preview')->name('preview');
});

Route::group(['namespace' => '/'],function(){
	//UserList
	Route::get('user_list',function(){
		return view('base_UI.admin.user_dashboard');
	})->name('user_dash');
});

app/BaseAuth.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BaseAuth extends Model
{
    //
}

app/Http/Controllers/BaseAuthController.php
<?php

namespace App\Http\Controllers;

use App\BaseAuth;
use Illuminate\Http\Request;
use Hash;
use App\User;

class BaseAuthController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('base_auth.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $insert_arr = [
            'name'              =>  $request->name,
            'email'             =>  $request->email,
            'password'          =>  Hash::make($request->password),
            'remember_token'    =>  csrf_token()
        ];
        $check = ($request->has('check') && $request->check) ? true:false;

        User::create($insert_arr,$check);

        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\BaseAuth  $baseAuth
     * @return \Illuminate\Http\Response
     */
    public function show(BaseAuth $baseAuth)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\BaseAuth  $baseAuth
     * @return \Illuminate\Http\Response
     */
    public function edit(BaseAuth $baseAuth)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\BaseAuth  $baseAuth
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BaseAuth $baseAuth)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\BaseAuth  $baseAuth
     * @return \Illuminate\Http\Response
     */
    public function destroy(BaseAuth $baseAuth)
    {
        //
    }
}

resources/views/base_auth/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Authentication Form for Registration</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<div class="card">
		<div class="card-header">
			<h6>Authentication Form for Registration</h6>
		</div>
		<div class="card-body">
			<form action="{{ route('base_form_post') }}" method="POST">
				{{ csrf_field() }}
				<h6>UserName:</h6><input type="text" name="name" placeholder="Enter Your UserName" class="form-control">
				<br>
				<h6>Email:</h6><input type="email" name="email" class="form-control" placeholder="Enter Your Email">
				<br>
				<h6>Password:</h6><input type="password" name="password" class="form-control" placeholder="Enter Your Password">
				<br>
				<input type="checkbox" name="check" value="check">
				<br>
				<input type="submit" name="submit" value="Save" class="btn mt-2 mb-2">
			</form>
		</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

resources/views/base_auth/logged_in.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>LoggedIn</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	@if (Session::has('msg'))		
		<div class="alert alert-success">
			<h6>{{ Session::get('msg') }}</h6>
		</div>
	@endif
	<table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
              	<th>#</th>
              	<th>Name</th>
              	<th>Email</th>
                @if(Auth::user() && Auth::user()->user_type==1)
                    <th>Action</th>
                @endif
            </tr>
        </thead>
        <tbody>
            <tr>   
                <td>{{ Auth::user()->id }}</td>
                <td>{{ Auth::user()->name }}</td>
                <td>{{ Auth::user()->email }}</td>
                <td>
                	@if (Auth::user()->user_type != 1)
	            		<a class="ml-2 mr-2" href="{{ route('user_dash',Auth::user()->id) }}">User List</a>
                	@else
	            		<a class="ml-2 mr-2" href="{{ route('user_dash',Auth::user()->id) }}">User List</a>
		        		<a class="ml-2 mr-2" href="{{ route('nav.index',Auth::user()->id) }}">Nav</a>
		                <a class="ml-2 mr-2" href="{{ route('body.index',Auth::user()->id) }}">Body</a>
		                <a class="ml-2 mr-2" href="{{ route('sidebar.index',Auth::user()->id) }}">SideBar</a>
		                <a class="ml-2 mr-2" href="{{ route('footer.index',Auth::user()->id) }}">Footer</a>
		                <a class="ml-2 mr-2" href="{{ route('report.index',Auth::user()->id) }}">Report Upload</a>
		                <a class="ml-2 mr-2" href="{{ route('service.index',Auth::user()->id) }}">Service Attributes</a>  
            		@endif
            	</td> 
            </tr>
        </tbody>
    </table>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

resources/views/base_auth/login.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Login Form</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<div class="card">
		<div class="card-header">
			<h6>Simple Login Form</h6>
		</div>
		<div class="card-body">
			<form action="{{ route('base_login_post') }}" method="POST">
				{{ csrf_field() }}
				<h6>UserName/Email:</h6><input type="text" name="login" class="form-control" placeholder="Enter Login Credentials">
				<br>
				<h6>Password:</h6><input type="password" name="password" class="form-control" placeholder="Enter Your Password">
				<br>
				<input type="checkbox" name="check" value="check">
				<br>
				<input type="submit" name="submit" value="SaveLogin" class="btn mt-2 mb-2">
			</form>
		</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>